### ISSUE TITLE
Visual Bug: Gradient of Hero 

### ISSUE THREAD

**Issue by nathan-barrett** [mozmeao/MIECO#22]
Gradient behind the text in the Hero on MIECO landing page should expand to the top left corner rather than just around the heading

![image](https://user-images.githubusercontent.com/30009669/222280975-d2b3cfef-bc80-4c8a-8af0-b2578f7514eb.png)

**Comment by stevejalim** [comment]
For the Birdbox-based version of future.m.o, Craig and I added a bit more padding around the text, which hopefully is enough:

<img width="693" alt="Screenshot 2023-11-07 at 14 09 15" src="https://github.com/mozmeao/MIECO/assets/101457/25e292c3-abce-4c3f-9488-c6daf75e0834">
