### ISSUE TITLE
5/8 Updates: Judges & Speakers

### ISSUE THREAD

**Issue by nathan-barrett** [mozmeao/MIECO#48]
## Whats should be added
1. adding the speakers & judges section (currently in figma, but still need copy and images)
2. adding in the top 10 finalist projects (should match the layout of the speakers section)
3. updating the partner logo section (need new logos for missing partner companies)

Content doc from innovations team: https://docs.google.com/document/d/1GMnKNKrsvEHW55SHSgbB3NDj6Z8O2qTvPZ_bY9a-WxU/edit?usp=sharing

**Comment by reemhamz** [comment]
Closed with #49
